/*
 * effx API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateEventPayloadIntegration struct for CreateEventPayloadIntegration
type CreateEventPayloadIntegration struct {
	Name string `json:"name"`
}

// NewCreateEventPayloadIntegration instantiates a new CreateEventPayloadIntegration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEventPayloadIntegration(name string, ) *CreateEventPayloadIntegration {
	this := CreateEventPayloadIntegration{}
	this.Name = name
	return &this
}

// NewCreateEventPayloadIntegrationWithDefaults instantiates a new CreateEventPayloadIntegration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEventPayloadIntegrationWithDefaults() *CreateEventPayloadIntegration {
	this := CreateEventPayloadIntegration{}
	return &this
}

// GetName returns the Name field value
func (o *CreateEventPayloadIntegration) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEventPayloadIntegration) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEventPayloadIntegration) SetName(v string) {
	o.Name = v
}

func (o CreateEventPayloadIntegration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCreateEventPayloadIntegration struct {
	value *CreateEventPayloadIntegration
	isSet bool
}

func (v NullableCreateEventPayloadIntegration) Get() *CreateEventPayloadIntegration {
	return v.value
}

func (v *NullableCreateEventPayloadIntegration) Set(val *CreateEventPayloadIntegration) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEventPayloadIntegration) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEventPayloadIntegration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEventPayloadIntegration(val *CreateEventPayloadIntegration) *NullableCreateEventPayloadIntegration {
	return &NullableCreateEventPayloadIntegration{value: val, isSet: true}
}

func (v NullableCreateEventPayloadIntegration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEventPayloadIntegration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


