/*
 * effx API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TeamConfiguration struct for TeamConfiguration
type TeamConfiguration struct {
	Version string `json:"version"`
	Kind string `json:"kind"`
	Spec TeamConfigurationSpec `json:"spec"`
}

// NewTeamConfiguration instantiates a new TeamConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamConfiguration(version string, kind string, spec TeamConfigurationSpec, ) *TeamConfiguration {
	this := TeamConfiguration{}
	this.Version = version
	this.Kind = kind
	this.Spec = spec
	return &this
}

// NewTeamConfigurationWithDefaults instantiates a new TeamConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamConfigurationWithDefaults() *TeamConfiguration {
	this := TeamConfiguration{}
	return &this
}

// GetVersion returns the Version field value
func (o *TeamConfiguration) GetVersion() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *TeamConfiguration) GetVersionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *TeamConfiguration) SetVersion(v string) {
	o.Version = v
}

// GetKind returns the Kind field value
func (o *TeamConfiguration) GetKind() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *TeamConfiguration) GetKindOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *TeamConfiguration) SetKind(v string) {
	o.Kind = v
}

// GetSpec returns the Spec field value
func (o *TeamConfiguration) GetSpec() TeamConfigurationSpec {
	if o == nil  {
		var ret TeamConfigurationSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *TeamConfiguration) GetSpecOk() (*TeamConfigurationSpec, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *TeamConfiguration) SetSpec(v TeamConfigurationSpec) {
	o.Spec = v
}

func (o TeamConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["version"] = o.Version
	}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableTeamConfiguration struct {
	value *TeamConfiguration
	isSet bool
}

func (v NullableTeamConfiguration) Get() *TeamConfiguration {
	return v.value
}

func (v *NullableTeamConfiguration) Set(val *TeamConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamConfiguration(val *TeamConfiguration) *NullableTeamConfiguration {
	return &NullableTeamConfiguration{value: val, isSet: true}
}

func (v NullableTeamConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


