/*
 * effx API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateEventPayloadActions struct for CreateEventPayloadActions
type CreateEventPayloadActions struct {
	Level string `json:"level"`
	Name string `json:"name"`
	Url string `json:"url"`
}

// NewCreateEventPayloadActions instantiates a new CreateEventPayloadActions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEventPayloadActions(level string, name string, url string, ) *CreateEventPayloadActions {
	this := CreateEventPayloadActions{}
	this.Level = level
	this.Name = name
	this.Url = url
	return &this
}

// NewCreateEventPayloadActionsWithDefaults instantiates a new CreateEventPayloadActions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEventPayloadActionsWithDefaults() *CreateEventPayloadActions {
	this := CreateEventPayloadActions{}
	return &this
}

// GetLevel returns the Level field value
func (o *CreateEventPayloadActions) GetLevel() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *CreateEventPayloadActions) GetLevelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *CreateEventPayloadActions) SetLevel(v string) {
	o.Level = v
}

// GetName returns the Name field value
func (o *CreateEventPayloadActions) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEventPayloadActions) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEventPayloadActions) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *CreateEventPayloadActions) GetUrl() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateEventPayloadActions) GetUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateEventPayloadActions) SetUrl(v string) {
	o.Url = v
}

func (o CreateEventPayloadActions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["level"] = o.Level
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableCreateEventPayloadActions struct {
	value *CreateEventPayloadActions
	isSet bool
}

func (v NullableCreateEventPayloadActions) Get() *CreateEventPayloadActions {
	return v.value
}

func (v *NullableCreateEventPayloadActions) Set(val *CreateEventPayloadActions) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEventPayloadActions) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEventPayloadActions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEventPayloadActions(val *CreateEventPayloadActions) *NullableCreateEventPayloadActions {
	return &NullableCreateEventPayloadActions{value: val, isSet: true}
}

func (v NullableCreateEventPayloadActions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEventPayloadActions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


