/*
 * effx API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// EventsApiService is a service that implents the logic for the EventsApiServicer
// This service should implement the business logic for every endpoint for the EventsApi API. 
// Include any external packages or services that will be required by this service.
type EventsApiService struct {
}

// NewEventsApiService creates a default api service
func NewEventsApiService() EventsApiServicer {
	return &EventsApiService{}
}

// EventsPost - 
func (s *EventsApiService) EventsPost(ctx context.Context, xEffxApiKey string, createEventPayload CreateEventPayload) (ImplResponse, error) {
	// TODO - update EventsPost with the required logic for this service method.
	// Add api_events_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	//return Response(403, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("EventsPost method not implemented")
}

