/*
 * effx API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A ConfigApiController binds http requests to an api service and writes the service results to the http response
type ConfigApiController struct {
	service ConfigApiServicer
}

// NewConfigApiController creates a default api controller
func NewConfigApiController(s ConfigApiServicer) Router {
	return &ConfigApiController{ service: s }
}

// Routes returns all of the api route for the ConfigApiController
func (c *ConfigApiController) Routes() Routes {
	return Routes{ 
		{
			"ConfigLint",
			strings.ToUpper("Post"),
			"/v2/config/lint",
			c.ConfigLint,
		},
		{
			"ConfigPut",
			strings.ToUpper("Put"),
			"/v2/config",
			c.ConfigPut,
		},
	}
}

// ConfigLint - 
func (c *ConfigApiController) ConfigLint(w http.ResponseWriter, r *http.Request) { 
	configurationFile := &ConfigurationFile{}
	if err := json.NewDecoder(r.Body).Decode(&configurationFile); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ConfigLint(r.Context(), *configurationFile)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ConfigPut - 
func (c *ConfigApiController) ConfigPut(w http.ResponseWriter, r *http.Request) { 
	configurationFile := &ConfigurationFile{}
	if err := json.NewDecoder(r.Body).Decode(&configurationFile); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.ConfigPut(r.Context(), *configurationFile)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}
