/*
 * effx API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ServiceConfiguration struct {

	Version string `json:"version"`

	Kind string `json:"kind"`

	Spec ServiceConfigurationSpec `json:"spec"`
}
