/*
 * effx API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateEventPayload struct {

	Message string `json:"message"`

	Title string `json:"title"`

	// the timestamp in milliseconds on which this event occurred. must be greater than 01/01/2020. If not specified, it will default to the timestamp on which the request was received.
	TimestampMilliseconds int64 `json:"timestamp_milliseconds,omitempty"`

	Tags []CreateEventPayloadTags `json:"tags,omitempty"`

	Actions []CreateEventPayloadActions `json:"actions,omitempty"`

	// the service's name that this event belongs to
	ServiceName string `json:"service_name,omitempty"`
}
