/*
 * effx API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2001 struct {

	Teams []Team `json:"teams,omitempty"`

	Pagination Pagination `json:"pagination,omitempty"`
}
